<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rasti1.TaskPlanner.Domain.Models\Rasti1.TaskPlanner.Domain.Models..csproj" />
  </ItemGroup>

</Project>
